// Mapping từ tên file không dấu sang tiếng Việt có dấu
export const vietnameseMapping: Record<string, string> = {
  // ===== BÀI 1: NGƯỜI THÂN, GIA ĐÌNH =====
  'anh': 'anh',
  'chi': 'chị',
  'em': 'em',
  'ba': 'ba',
  'me': 'mẹ',
  'ong': 'ông',
  'chau': 'cháu',
  'con': 'con',
  'bo': 'bố',
  'vo': 'vợ',
  'ban': 'bạn',
  'anh_chi': 'anh chị',
  'anh_chi_em': 'anh chị em',
  'anh_em': 'anh em',
  'anh_hai_anh_ca': 'anh hai/anh cả',
  'anh_ho': 'anh họ',
  'anh_re': 'anh rể',
  'anh_ruot': 'anh ruột',
  'anh_vo': 'anh vợ',
  'chi_hai_chi_ca': 'chị hai/chị cả',
  'chi_ho': 'chị họ',
  'chau_ho': 'cháu họ',
  'em_ho': 'em họ',
  'ong_ba': 'ông bà',
  'ban_gai': 'bạn gái',
  'ban_trai': 'bạn trai',
  'ban_than': 'bạn thân',
  'tre_con_con_nit': 'trẻ con/con nít',
  'binh_sua_em_be': 'bình sữa em bé',

  // ===== BÀI 2: ẨM THỰC =====
  // Món ăn
  'banh_canh': 'bánh canh',
  'banh_hamburger': 'bánh hamburger',
  'banh_sandwich': 'bánh sandwich',
  'banh_trang': 'bánh tráng',
  'bun_cha': 'bún chả',
  'bun_dau': 'bún đậu',
  'bun_mam': 'bún mắm',
  'bun_ngan': 'bún ngán',
  'bun_oc': 'bún ốc',
  'com_rang': 'cơm rang',
  'my_tom': 'mỳ tôm',
  'my_y': 'mỳ Ý',
  'my_van_than': 'mỳ vằn thắn',
  'bit_tet_bo': 'bít tết bò',
  'vit_quay': 'vịt quay',
  'ga_nuong_lu': 'gà nướng lu',
  'xoi_ga': 'xôi gà',
  'xoi_gac': 'xôi gấc',
  'chao_suon': 'cháo sườn',
  'goi_nom': 'gỏi/nộm',
  'sup': 'súp',
  'sup_do': 'súp đỏ',
  'sup_lo': 'súp lơ',
  'cho_xoi': 'chợ xôi',
  'lẩu': 'lẩu',
  'hap': 'hấp',
  'nuong': 'nướng',
  'xao': 'xào',
  // Đồ uống
  'tra_da': 'trà đá',
  'tra_nong': 'trà nóng',
  'tra_sua': 'trà sữa',
  'chanh_da': 'chanh đá',
  'chanh_muoi': 'chanh muối',
  'chanh_nong': 'chanh nóng',
  'sinh_to_bo_dau': 'sinh tố bơ dâu',
  'nuoc_ep_trai_cay': 'nước ép trái cây',
  'nuoc_ep_cam_ca_chua': 'nước ép cam/cà chua',
  'nuoc_mam': 'nước mắm',
  'Cocacola': 'Coca Cola',
  'cocacola': 'Coca Cola',
  'Socola': 'Sô cô la',
  'socola': 'Sô cô la',
  '7up': '7up',
  // Nguyên liệu
  'tuong_ot': 'tương ớt',
  'rau_diep_ca': 'rau diếp cá',
  'rau_ngo_rau_mui': 'rau ngò/rau mùi',
  'vat_chanh': 'vắt chanh',
  'do_an': 'đồ ăn',
  'do_uong': 'đồ uống',
  'hai_san': 'hải sản',
  'tom_hum': 'tôm hùm',

  // ===== BÀI 3: CÁC QUỐC GIA =====
  'albania_nuoc_albania': 'Albania (nước Albania)',
  'anh_nuoc_anh': 'Anh (nước Anh)',
  'du_bai_nuoc_du_bai': 'Dubai (nước Dubai)',
  'ma_lai_nuoc_ma_lai_xi_a': 'Malaysia (nước Malaysia)',
  'ma_cao': 'Ma Cao',
  'mien_dien_nuoc_mi_an_ma': 'Miến Điện (nước Myanmar)',
  'a_rap_nuoc_a_rap': 'Ả Rập (nước Ả Rập)',
  'do_thai': 'Do Thái',
  'phuong_dong': 'phương Đông',
  'phuong_tay': 'phương Tây',
  // Địa danh Việt Nam
  'bac_lieu': 'Bạc Liêu',
  'ba_ria_vung_tau': 'Bà Rịa - Vũng Tàu',
  'an_giang': 'An Giang',
  'quy_nhon': 'Quy Nhơn',
  'tuy_hoa': 'Tuy Hòa',
  'co_do_hue': 'cố đô Huế',
  'thang_long': 'Thăng Long',
  'ba_na': 'Bà Nà',
  'cang_hai_phong': 'cảng Hải Phòng',
  'cang_sai_gon': 'cảng Sài Gòn',
  've_sai_gon': 'về Sài Gòn',
  'bai_bien_vung_tau': 'bãi biển Vũng Tàu',
  'chua_yen_tu': 'chùa Yên Tử',
  'day_nui_hoang_lien_son': 'dãy núi Hoàng Liên Sơn',
  'dong_bang_song_hong': 'đồng bằng sông Hồng',
  'dong_bang_song_cuu_long': 'đồng bằng sông Cửu Long',
  'dong_bang_duyen_hai_mien_trung': 'đồng bằng duyên hải miền Trung',
  'cau_the_huc_ho_guom': 'cầu Thê Húc - Hồ Gươm',
  'sa_mac': 'sa mạc',
  'thung_lung': 'thung lũng',
  'viet_nam': 'Việt Nam',
  'yeu_nuoc_viet_nam': 'yêu nước Việt Nam',

  // ===== BÀI 4: ĐỘNG VẬT =====
  'ca': 'cá',
  'cho': 'chó',
  'meo': 'mèo',
  'voi': 'voi',
  'ga': 'gà',
  'vit': 'vịt',
  'chuot': 'chuột',
  'hau': 'hàu',
  'tom': 'tôm',
  'ca_kiem': 'cá kiếm',
  'con_ca_sau': 'con cá sấu',
  'con_hau': 'con hàu',
  'con_vuon': 'con vượn',
  'duoi_ca': 'đuôi cá',
  'duoi_chuot': 'đuôi chuột',
  'canh_buom': 'cánh bướm',
  'cai_vot_ca': 'cái vợt cá',
  'noi_da_ga': 'nổi da gà',
  'rang_ho': 'răng hổ',

  // ===== BÀI 5: PHƯƠNG TIỆN =====
  'xe': 'xe',
  'may_bay': 'máy bay',
  'tau': 'tàu',
  'xe_container': 'xe container',
  'hang_may_bay': 'hãng máy bay',
  'bay_nhanh_may_bay': 'bay nhanh (máy bay)',
  'may_xuc': 'máy xúc',
  'bai_do_xe_o_to': 'bãi đỗ xe ô tô',
  'internet': 'internet',

  // ===== BÀI 6: HÀNH ĐỘNG =====
  'danh_cau_long': 'đánh cầu lông',
  'danh_rang': 'đánh răng',
  'rua_chan': 'rửa chân',
  'rua_mat': 'rửa mặt',
  'luoc': 'luộc',
  'luoc_rau': 'luộc rau',
  'nau_nuong': 'nấu nướng',
  'lau': 'lau',
  'lau_mieng': 'lau miệng',
  'moc_rau': 'mọc râu',
  'moc_ria_mep': 'mọc ria mép',
  'moc_toc': 'mọc tóc',
  'cat_long_mui': 'cắt lông mũi',
  'nho_long_may': 'nhổ lông mày',
  'nho_rang': 'nhổ răng',
  'nho_rau': 'nhổ râu',
  'nho_toc': 'nhổ tóc',
  'trang_diem': 'trang điểm',
  'di_dao': 'đi dạo',
  'di_tuan': 'đi tuần',
  'di_ve_sinh': 'đi vệ sinh',
  'nhay_bao_bo': 'nhảy bao bố',
  'nhay_lo_co': 'nhảy lò cò',
  'chay_dong_vat': 'chạy (động vật)',
  'ban_chai_danh_rang': 'bàn chải đánh răng',
  'vot_cau_long': 'vợt cầu lông',
  'keo_co': 'kéo co',
  'cam_trai': 'cắm trại',
  'tron_tim': 'trốn tìm',
  'xoa_dau': 'xoa đầu',
  'nham_mat': 'nhắm mắt',
  'liec_nhin': 'liếc nhìn',
  'ngung_lai': 'ngừng lại',
  'dung_lai': 'dừng lại',
  'xay_ra': 'xảy ra',
  'quan_sat': 'quan sát',
  'giam_sat': 'giám sát',
  'an': 'ăn',
  'an_uong': 'ăn uống',
  'hoi': 'hỏi',
  'hua': 'hứa',
  'luom': 'lượm',
  'xem_da': 'xem đá',
  'thi_tham': 'thì thầm',

  // ===== TỪ PHỔ BIẾN KHÁC =====
  // Từ đơn
  'ac': 'ác',
  'dang': 'đang',
  'doi': 'đói',
  'đòi': 'đòi',
  'dua': 'dừa',
  'gio': 'gió',
  'hen': 'hẹn',
  'hoac': 'hoặc',
  'hoan': 'hoãn',
  'huy': 'hủy',
  'kia': 'kia',
  'mach': 'mạch',
  'mia': 'mía',
  'mien': 'miễn',
  'muoi': 'muối',
  'ngan': 'ngán',
  'nhung': 'nhưng',
  'so': 'sợ',
  'suỵt': 'suỵt',
  'them': 'thêm',
  'thiu': 'thiu',
  'thoi': 'thôi',
  'tinh': 'tỉnh',
  'van': 'vẫn',
  'nguoi': 'người',
  
  // Từ đôi
  'ac_cam': 'ác cảm',
  'ac_doc': 'ác độc',
  'ac_mong': 'ác mộng',
  'ai_cho': 'ai cho',
  'am_ap': 'ấm áp',
  'am_dun_nuoc': 'ấm đun nước',
  'am_i': 'âm ỉ',
  'am_moc': 'ẩm mốc',
  'am_no': 'ấm no',
  'am_thanh': 'âm thanh',
  'am_tra': 'ấm trà',
  'am_uot': 'ẩm ướt',
  'anh_dung': 'anh dũng',
  'anh_hung': 'anh hùng',
  'an_bam': 'ăn bám',
  'an_coc': 'ăn cóc',
  'an_dien': 'ăn diện',
  'an_du': 'ăn dư',
  'an_han': 'ăn hận',
  'an_hoi_lo': 'ăn hối lộ',
  'an_it': 'ăn ít',
  'an_ninh': 'an ninh',
  'an_tuong': 'ấn tượng',
  'an_vat': 'ăn vặt',
  'an_vua': 'ăn vừa',
  'an_vung': 'ăn vụng',
  'an_vu_sua': 'ăn vú sữa',
  'an_xin': 'ăn xin',
  'ao_am': 'áo ấm',
  'ao_canh': 'áo cánh',
  'ao_chuom': 'áo choàng',
  'ao_len': 'áo len',
  'ao_phao': 'áo phao',
  'ao_phong': 'áo phông',
  'ao_thuat': 'ảo thuật',
  'ap_phich': 'áp phích',
  'au_co': 'Âu Cơ',
  'bai_bao': 'bài báo',
  'bai_cat': 'bãi cát',
  'bai_co': 'bãi cỏ',
  'bai_tam': 'bãi tắm',
  'bai_tho': 'bài thơ',
  'bang_chia': 'bảng chia',
  'bang_cong': 'bảng cộng',
  'bang_den': 'bảng đen',
  'bang_mau': 'bảng màu',
  'bang_nhan': 'bảng nhân',
  'ban_bac': 'bàn bạc',
  'ban_buon': 'bán buôn',
  'ban_chan': 'bàn chân',
  'ban_dao': 'bán đảo',
  'ban_dem': 'ban đêm',
  'ban_ghe': 'bàn ghế',
  'ban_hang': 'bán hàng',
  'ban_la': 'bàn là',
  'ban_lang': 'bản làng',
  'ban_le': 'bán lẻ',
  'ban_ngay': 'ban ngày',
  'ban_nhac': 'ban nhạc',
  'ban_sao': 'bản sao',
  'ban_tan': 'bàn tán',
  'ban_tay': 'bàn tay',
  'bat_khuat': 'bất khuất',
  'ba_la': 'ba lá',
  'boi_roi': 'bối rối',
  'bon_la': 'bốn lá',
  'buc_minh': 'bực mình',
  'buon_tham': 'buồn thảm',
  'cach_ly': 'cách ly',
  'cai_gui': 'cái gùi',
  'cai_neo': 'cái neo',
  'cam_thu': 'căm thù',
  'canh_giac': 'cảnh giác',
  'canh_tranh': 'cạnh tranh',
  'ca_ngay': 'cả ngày',
  'cham_chap': 'chậm chạp',
  'chia_ba': 'chia ba',
  'chia_doi': 'chia đôi',
  'chia_re': 'chia rẽ',
  'cho_can': 'chó cắn',
  'cong_nghiep': 'công nghiệp',
  'con_ban': 'còn bạn',
  'co_vy_covid': 'COVID-19',
  'cua_dong': 'cửa đông',
  'cuc_kho': 'cực khổ',
  'cung_cap': 'cung cấp',
  'cung_dien': 'cung điện',
  'cung_ten': 'cùng tên',
  'cuoi_nam': 'cuối năm',
  'cuoi_thang': 'cuối tháng',
  'cuoi_tuan': 'cuối tuần',
  'cuu_song': 'cứu sống',
  'dai_su': 'đại sứ',
  'dam_lam': 'dám làm',
  'dang_hoang': 'đàng hoàng',
  'dan_chu': 'dân chủ',
  'dao_dien': 'đạo diễn',
  'dat_ruong': 'đất ruộng',
  'dau_bung': 'đau bụng',
  'dau_chan': 'dấu chân',
  'dau_mat': 'đau mắt',
  'dau_tai': 'đau tai',
  'dau_tay': 'đau tay',
  'dau_tu': 'đầu tư',
  'da_trang': 'da trắng',
  'den_dui': 'đen đủi',
  'dia_chi': 'địa chỉ',
  'dia_hinh': 'địa hình',
  'diu_dang': 'dịu dàng',
  'doi_cap': 'đôi cặp',
  'doi_hoi': 'đòi hỏi',
  'du_an': 'dự án',
  'dum_boc': 'đùm bọc',
  'duy_nhat': 'duy nhất',
  'gap_ba': 'gấp ba',
  'gap_doi': 'gấp đôi',
  'ghen_ti': 'ghen tị',
  'gian_doi': 'gian dối',
  'gop_tien': 'góp tiền',
  'hai_la': 'hai lá',
  'hai_long': 'hài lòng',
  'ham_choi': 'ham chơi',
  'hang_ngay': 'hàng ngày',
  'hao_huc': 'háo hức',
  'hap_dan': 'hấp dẫn',
  'hoi_dau': 'hơi đau',
  'hoi_thoai': 'hội thoại',
  'hop_nhom': 'họp nhóm',
  'hot_hoang': 'hốt hoảng',
  'hung_vi': 'hùng vĩ',
  'huu_nghi': 'hữu nghị',
  'hu_via': 'hú vía',
  'ket_luan': 'kết luận',
  'kha_nang': 'khả năng',
  'khoi_nghiep': 'khởi nghiệp',
  'khong_can': 'không cần',
  'khong_cho': 'không cho',
  'khong_co': 'không có',
  'khong_dam': 'không dám',
  'khong_dep': 'không đẹp',
  'khong_muon': 'không muốn',
  'khong_nen': 'không nên',
  'khong_ngon': 'không ngon',
  'khong_quen': 'không quên',
  'kho_cong': 'khó công',
  'kho_dai': 'khó đại',
  'kim_cuong': 'kim cương',
  'kim_dong': 'Kim Đồng',
  'kip_thoi': 'kịp thời',
  'ky_nang': 'kỹ năng',
  'lam_duoc': 'làm được',
  'lam_lem': 'lem lém',
  'lang_phi': 'lãng phí',
  'lanh_lung': 'lạnh lùng',
  'loc_xoay': 'lốc xoáy',
  'long_vuong': 'long vương',
  'lung_tung': 'lúng túng',
  'luot_di': 'lượt đi',
  'ly_do': 'lý do',
  'may_man': 'may mắn',
  'ma_hong': 'má hồng',
  'meo_cao': 'mèo cao',
  'met_moi': 'mệt mỏi',
  'mit_tinh': 'mít tinh',
  'moi_ngay': 'mỗi ngày',
  'mo_ta': 'mô tả',
  'muc_tieu': 'mục tiêu',
  'mui_ten': 'mũi tên',
  'mum_mim': 'mũm mĩm',
  'mu_chu': 'mù chữ',
  'nam_la': 'năm lá',
  'nam_toi': 'năm tới',
  'nan_ni': 'năn nỉ',
  'nha_kho': 'nhà kho',
  'nha_rong': 'nhà rông',
  'nhut_nhat': 'nhút nhát',
  'nong_tinh': 'nóng tính',
  'nui_cao': 'núi cao',
  'nui_thap': 'núi thấp',
  'phien_ha': 'phiền hà',
  'phong_toa': 'phong tỏa',
  'phong_vien': 'phóng viên',
  'phu_thuoc': 'phụ thuộc',
  'quanh_nam': 'quanh năm',
  'quyen_gop': 'quyên góp',
  'rac_roi': 'rắc rối',
  'rang_khenh': 'răng khểnh',
  'ria_mep': 'ria mép',
  'ruc_ro': 'rực rỡ',
  'sinh_doi': 'sinh đôi',
  'song_sot': 'sống sót',
  'tai_ve': 'tải về',
  'tan_so': 'tần số',
  'tay_chay': 'tẩy chay',
  'tham_an': 'thăm an',
  'thao_thuc': 'thao thức',
  'thap_den': 'tháp đèn',
  'them_ro_dai': 'thêm rồ dài',
  'thieu_thon': 'thiếu thốn',
  'thinh_vuong': 'thịnh vượng',
  'thoi_quen': 'thói quen',
  'thuoc_dia': 'thuộc địa',
  'thuong_mai': 'thương mại',
  'tien_bo': 'tiến bộ',
  'tiep_tan': 'tiếp tân',
  'tinh_mat': 'tỉnh mắt',
  'tinh_tao': 'tỉnh táo',
  'toc_dai': 'tóc dài',
  'toc_ngan': 'tóc ngắn',
  'trieu_phu': 'triệu phú',
  'trong_nha': 'trong nhà',
  'tuan_nay': 'tuần này',
  'tuan_sau': 'tuần sau',
  'tuan_truoc': 'tuần trước',
  'tuong_lai': 'tương lai',
  'tu_choi': 'từ chối',
  'tu_giac': 'tự giác',
  'tu_hao': 'tự hào',
  'tu_trong': 'tự trọng',
  'ung_thu': 'ung thư',
  'vai_lua': 'vải lụa',
  'vo_duyen': 'vô duyên',
  'vo_tinh': 'vô tình',
  'vo_ve': 'vỗ về',
  'xu_ly': 'xử lý',
  'xui_xeo': 'xui xẻo',

  // ===== CÂU/CỤM TỪ (ADVANCED) =====
  '2_5_toan_hoc': '2/5 (toán học)',
  '2_6_toan_hoc': '2/6 (toán học)',
  '5_3_toan_hoc': '5/3 (toán học)',
  'an_vu_sua_bang_thia': 'ăn vú sữa bằng thìa',
  'ao_dong_phuc': 'áo đồng phục',
  'ao_ke_soc': 'áo kẻ sọc',
  'ba_chan_bon_cang': 'ba chân bốn cẳng',
  'ban_ay_yeu_ban': 'bạn ấy yêu bạn',
  'ban_ay_yeu_toi': 'bạn ấy yêu tôi',
  'ban_cung_ten': 'bạn cùng tên',
  'ban_do_viet_nam': 'bản đồ Việt Nam',
  'ban_giam_hieu': 'ban giám hiệu',
  'ban_kinh_hinh_tron': 'bán kính hình tròn',
  'ban_phim_may_vi_tinh': 'bàn phím máy vi tính',
  'ban_sao_chi_nguoi': 'bản sao (chỉ người)',
  'ban_yeu_ban_ay': 'bạn yêu bạn ấy',
  'ban_yeu_toi': 'bạn yêu tôi',
  'bang_chi_dan': 'bảng chỉ dẫn',
  'bang_chu_cai_ngon_tay': 'bảng chữ cái ngón tay',
  'bang_cuu_chuong': 'bảng cửu chương',
  'bang_hoc_sinh': 'bảng học sinh',
  'benh_dao_down': 'bệnh đao Down',
  'benh_phong_cui': 'bệnh phong cùi',
  'cac_ban_2_nguoi': 'các bạn (2 người)',
  'can_khong_': 'cần không?',
  'chien_ran_12': 'chiên/rán (12)',
  'chung_tay': 'chung tay',
  'chung_toi_2_nguoi_dai_tu': 'chúng tôi (2 người - đại từ)',
  'chung_toi_3_nguoi_dai_tu': 'chúng tôi (3 người - đại từ)',
  'chung_toi_4_nguoi_dai_tu': 'chúng tôi (4 người - đại từ)',
  'chung_toi_5_nguoi_dai_tu': 'chúng tôi (5 người - đại từ)',
  'chung_toi_dai_tu': 'chúng tôi (đại từ)',
  'chuyen_lon': 'chuyện lớn',
  'chuyen_nho': 'chuyện nhỏ',
  'co_khong_': 'có không?',
  'cung_vay_cung_the': 'cũng vậy/cũng thế',
  'cung_voi_gioi_tu': 'cùng với (giới từ)',
  'cuoi_nhech_mep': 'cười nhếch mép',
  'cuoi_vo_bung': 'cười vỡ bụng',
  'dan_toc_cham': 'dân tộc Chăm',
  'dan_toc_kho_me': 'dân tộc Khơ Me',
  'dan_toc_mong': 'dân tộc Mông',
  'dan_toc_muong': 'dân tộc Mường',
  'dan_toc_thai': 'dân tộc Thái',
  'dat_nuoc_bi_chia_cat_viet_nam': 'đất nước bị chia cắt (Việt Nam)',
  'da_ngam_nuoc_da_ngam_den': 'da ngâm nước/da ngâm đen',
  'den_ong_sao': 'đèn ông sao',
  'dep_khong_': 'đẹp không?',
  'dep_khong_nguoi': 'đẹp không (người)?',
  'di_lac_duong_rung': 'đi lạc (đường rừng)',
  'doi_khong_': 'đói không?',
  'dong_song_chay': 'dòng sông chảy',
  'dung_dau_hang_dau': 'đứng đầu/hàng đầu',
  'dung_khong_': 'đúng không?',
  'gian_cach_xa_hoi': 'giãn cách xã hội',
  'hay_la_hoac_la': 'hay là/hoặc là',
  'hen_gap_may': 'hẹn gặp may',
  'he_bai_tiet': 'hệ bài tiết',
  'ho_2_nguoi_dai_tu': 'họ (2 người - đại từ)',
  'ho_dai_tu': 'họ (đại từ)',
  'hoi_chung_dao_down': 'hội chứng đao Down',
  'ket_xe_tac_duong': 'kẹt xe/tắc đường',
  'khau_khinh': 'khẩu khinh',
  'khoang_san': 'khoáng sản',
  'khong_binh_dang': 'không bình đẳng',
  'khong_co_chi': 'không có chi',
  'khong_nghe_loi': 'không nghe lời',
  'khu_vuc_cach_ly': 'khu vực cách ly',
  'khuyen_khich': 'khuyến khích',
  'le_halloween_31_10': 'lễ Halloween (31/10)',
  'long_lanh_mat': 'long lanh mắt',
  'lon_hon_1_toan_hoc': 'lớn hơn 1 (toán học)',
  'lon_hon_2_toan_hoc': 'lớn hơn 2 (toán học)',
  'luot_ve_trong_the_thao': 'lượt về (trong thể thao)',
  'mat_chet_chi_nguoi': 'mắt chết (chỉ người)',
  'met_khong_': 'mệt không?',
  'mo_hoi_nhe_nhai': 'mồ hôi nhễ nhại',
  'mot_it_mot_chut': 'một ít/một chút',
  'mot_la': 'một lá',
  'mot_tieng': 'một tiếng',
  'mot_tiet_hoc': 'một tiết học',
  'muon_khong_': 'muốn không?',
  'nen_khong_': 'nên không?',
  'ngap_ngung': 'ngập ngừng',
  'ngay_cua_cha': 'ngày của cha',
  'ngay_cua_me': 'ngày của mẹ',
  'ngay_giai_phong_mien_nam_30_4': 'Ngày Giải phóng miền Nam (30/4)',
  'ngay_giai_phong_thu_do_10_10': 'Ngày Giải phóng Thủ đô (10/10)',
  'ngay_gia_dinh_viet_nam_28_6': 'Ngày Gia đình Việt Nam (28/6)',
  'ngay_gio_to_hung_vuong_am_lich_10_3': 'Ngày Giỗ tổ Hùng Vương (âm lịch 10/3)',
  'ngay_ngon_ngu_ki_hieu_quoc_te_23_9': 'Ngày Ngôn ngữ ký hiệu quốc tế (23/9)',
  'ngay_nguoi_khuyet_tat_the_gioi_3_12': 'Ngày Người khuyết tật thế giới (3/12)',
  'ngay_nguoi_khuyet_tat_viet_nam_18_4': 'Ngày Người khuyết tật Việt Nam (18/4)',
  'ngay_phu_nu_viet_nam_20_10': 'Ngày Phụ nữ Việt Nam (20/10)',
  'ngay_quoc_te_phu_nu_8_3': 'Ngày Quốc tế Phụ nữ (8/3)',
  'ngay_thanh_lap_quan_doi_nhan_dan_viet_nam': 'Ngày thành lập Quân đội nhân dân Việt Nam',
  'ngay_thay_thuoc_viet_nam': 'Ngày Thầy thuốc Việt Nam',
  'ngay_thuong_binh_liet_si_27_7': 'Ngày Thương binh liệt sĩ (27/7)',
  'nghenh_nghenh_dau': 'nghênh nghênh đầu',
  'nguoi_nuoc_ngoai': 'người nước ngoài',
  'nha_van_hoa': 'nhà văn hóa',
  'nha_ve_sinh': 'nhà vệ sinh',
  'nhan_manh': 'nhấn mạnh',
  'nhan_vien': 'nhân viên',
  'nhap_khau': 'nhập khẩu',
  'nhon_nhip_dong_nguoi': 'nhộn nhịp đông người',
  'noi_ngap_ngung': 'nói ngập ngừng',
  'nut_ne_ruong': 'nứt nẻ ruộng',
  'o_lim_pic': 'Olympic',
  'phai_khong_': 'phải không?',
  'phan_biet': 'phân biệt',
  'phan_van': 'phân vân',
  'pho_hieu_truong': 'phó hiệu trưởng',
  'quan_chuc_vu': 'quân (chức vụ)',
  'quan_he_tu': 'quan hệ từ',
  'qua_bau_ho_lo': 'quả bầu hồ lô',
  'quyen_luyen': 'quyến luyến',
  'so_khong_': 'sợ không?',
  'so_la_ma_toan_hoc': 'số La Mã (toán học)',
  'suy_ra_toan_hoc': 'suy ra (toán học)',
  'tay_chan_sach_se': 'tay chân sạch sẽ',
  'tet_han_thuc': 'tết Hàn Thực',
  'tham_quang_mat': 'thâm quầng mắt',
  'thanh_giong': 'Thánh Gióng',
  'thi_nghiem': 'thí nghiệm',
  'thiep_sinh_nhat': 'thiệp sinh nhật',
  'thoat_thoat': 'thoát thoát',
  'thong_nhat_dat_nuoc': 'thống nhất đất nước',
  'thuong_xuyen': 'thường xuyên',
  'ti_hi_mat': 'ti hí mắt',
  'toi_yeu_ban_ay': 'tôi yêu bạn ấy',
  'tong_ket_be_giang': 'tổng kết/bế giảng',
  'trong_khoang': 'trong khoảng',
  'tuan_le_nguoi_diec_the_gioi': 'tuần lễ người điếc thế giới',
  'tuan_trang_mat': 'tuần trăng mật',
  'tuyen_truyen': 'tuyên truyền',
  'vo_thi_sau': 'Võ Thị Sáu',
  'vong_nguyet_que': 'vòng nguyệt quế',
  'xuyen_viet': 'xuyên Việt',
};

// Function để convert tên file không dấu sang có dấu
export function toVietnamese(text: string): string {
  // Normalize: remove .gif, lowercase, replace spaces with underscore
  const normalized = text.toLowerCase().replace('.gif', '').replace(/ /g, '_');
  
  // Lookup in mapping
  if (vietnameseMapping[normalized]) {
    return vietnameseMapping[normalized];
  }
  
  // Fallback: replace underscore with space and capitalize
  return text
    .replace(/_/g, ' ')
    .split(' ')
    .map(word => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ');
}
